version: '3.1'

services:
  blog_strapi_api:
    container_name: blog
    hostname: blog_strapi_api
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: blog-strapi
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
        - ~/.Downloads/backup/www/docker:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432